"""Flask API + static frontend server for CadastraAI.

Everything served here is computed from real data: live-fetched OpenStreetMap
vector layers, a real stitched satellite mosaic, a RandomForest model
actually trained on this machine, and a real shapely rule engine run against
that output. Run order: fetch_data.py -> fetch_imagery.py -> model.py -> app.py
"""
import json
from pathlib import Path

from flask import Flask, jsonify, send_from_directory
from flask_cors import CORS

import rules

BASE_DIR = Path(__file__).resolve().parent.parent
PROC_DIR = BASE_DIR / "data" / "processed"
FRONTEND_DIR = BASE_DIR / "frontend"

app = Flask(__name__, static_folder=None)
CORS(app)

_cache = {}


def _read_json(name):
    return json.loads((PROC_DIR / name).read_text(encoding="utf-8"))


def get_rule_results():
    if "rules" not in _cache:
        _cache["rules"] = rules.evaluate_all()
    return _cache["rules"]


@app.route("/")
def index():
    return send_from_directory(FRONTEND_DIR, "index.html")


@app.route("/vendor/<path:filename>")
def vendor(filename):
    return send_from_directory(FRONTEND_DIR / "vendor", filename)


@app.route("/api/meta")
def api_meta():
    meta = _read_json("meta.json")
    geo = _read_json("aoi_image_geo.json")
    return jsonify({"meta": meta, "image": geo})


@app.route("/api/image")
def api_image():
    return send_from_directory(PROC_DIR, "aoi_image.png")


@app.route("/api/layers")
def api_layers():
    return jsonify({
        "roads": _read_json("roads.geojson"),
        "railway": _read_json("railway.geojson"),
        "waterway": _read_json("waterway.geojson"),
        "government": _read_json("government.geojson"),
    })


@app.route("/api/osm_buildings")
def api_osm_buildings():
    return jsonify(_read_json("buildings.geojson"))


@app.route("/api/buildings")
def api_buildings():
    fc = _read_json("extracted_buildings.geojson")
    results_by_id = {r["id"]: r for r in get_rule_results()}
    for f in fc["features"]:
        r = results_by_id.get(f["properties"]["id"], {"alerts": [], "area_m2": None})
        f["properties"]["alerts"] = r["alerts"]
        f["properties"]["area_m2"] = r["area_m2"]
    return jsonify(fc)


@app.route("/api/metrics")
def api_metrics():
    return jsonify(_read_json("model_metrics.json"))


@app.route("/api/report/<int:building_id>")
def api_report(building_id):
    results = {r["id"]: r for r in get_rule_results()}
    r = results.get(building_id)
    if r is None:
        return jsonify({"error": "not found"}), 404

    lines = [
        "CADASTRAAI -- FIELD VERIFICATION NOTE",
        f"Ref: CADAI-BLDG-{building_id:04d}",
        f"Area under AOI: Igatpuri, Maharashtra (real OSM-derived boundary)",
        f"Footprint area (model-extracted): {r['area_m2']} m2",
        "",
    ]
    if r["alerts"]:
        lines.append("FINDINGS")
        for i, a in enumerate(r["alerts"], 1):
            lines.append(f"{i}. {a['type']}: {a['msg']}")
            lines.append(f"   Reference: {a['citation']}")
        lines.append("")
        lines.append("RECOMMENDED ACTION")
        lines.append("Route to the relevant department for field verification within 15 days.")
    else:
        lines.append("FINDINGS")
        lines.append("None. Footprint appears compliant against all automated checks.")
    lines.append("")
    lines.append("This note is generated by an automated analysis pipeline for planning /")
    lines.append("triage purposes. It is not a legal notice and requires field verification")
    lines.append("and authorized sign-off before any action.")

    return jsonify({"report": "\n".join(lines)})


if __name__ == "__main__":
    app.run(debug=True, port=5050)
