"""Bake the real pipeline's output into a static bundle Vercel (or any static
host) can serve with no backend at request time.

Run this locally after fetch_data.py / fetch_imagery.py / model.py. It does
NOT retrain or refetch anything -- it just runs the rule engine once, merges
the results into the building GeoJSON, precomputes every verification report,
and copies everything the frontend needs into frontend/data/.

The Flask app in app.py still works for local development (it recomputes
rules per-request); this script exists because Vercel's serverless functions
aren't a good fit for a RandomForest + shapely pipeline with in-memory state,
and none of that needs to be live anyway -- the model and rules only change
when you deliberately rerun them.
"""
import json
import shutil
from pathlib import Path

import parcels
import rules

BASE_DIR = Path(__file__).resolve().parent.parent
PROC_DIR = BASE_DIR / "data" / "processed"
OUT_DIR = BASE_DIR / "frontend" / "data"


def build_report(building_id, area_m2, alerts):
    lines = [
        "CADASTRAAI -- FIELD VERIFICATION NOTE",
        f"Ref: CADAI-BLDG-{building_id:04d}",
        "Area under AOI: Igatpuri, Maharashtra (real OSM-derived boundary)",
        f"Footprint area (model-extracted): {area_m2} m2",
        "",
    ]
    if alerts:
        lines.append("FINDINGS")
        for i, a in enumerate(alerts, 1):
            lines.append(f"{i}. {a['type']}: {a['msg']}")
            lines.append(f"   Reference: {a['citation']}")
        lines.append("")
        lines.append("RECOMMENDED ACTION")
        lines.append("Route to the relevant department for field verification within 15 days.")
    else:
        lines.append("FINDINGS")
        lines.append("None. Footprint appears compliant against all automated checks.")
    lines.append("")
    lines.append("This note is generated by an automated analysis pipeline for planning /")
    lines.append("triage purposes. It is not a legal notice and requires field verification")
    lines.append("and authorized sign-off before any action.")
    return "\n".join(lines)


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    print("Delineating land parcels...")
    parcels.main()

    print("Running rule engine...")
    rule_results = {r["id"]: r for r in rules.evaluate_all()}

    extracted_fc = json.loads((PROC_DIR / "extracted_buildings.geojson").read_text(encoding="utf-8"))
    reports = {}
    for f in extracted_fc["features"]:
        bid = f["properties"]["id"]
        r = rule_results.get(bid, {"alerts": [], "area_m2": None})
        f["properties"]["alerts"] = r["alerts"]
        f["properties"]["area_m2"] = r["area_m2"]
        reports[str(bid)] = build_report(bid, r["area_m2"], r["alerts"])

    (OUT_DIR / "buildings.geojson").write_text(json.dumps(extracted_fc), encoding="utf-8")
    (OUT_DIR / "reports.json").write_text(json.dumps(reports), encoding="utf-8")
    print(f"  {len(extracted_fc['features'])} buildings with baked-in alerts -> data/buildings.geojson")
    print(f"  {len(reports)} precomputed verification notes -> data/reports.json")

    shutil.copy(PROC_DIR / "buildings.geojson", OUT_DIR / "osm_buildings.geojson")
    shutil.copy(PROC_DIR / "model_metrics.json", OUT_DIR / "metrics.json")
    shutil.copy(PROC_DIR / "aoi_image.png", OUT_DIR / "image.png")
    shutil.copy(PROC_DIR / "parcels.geojson", OUT_DIR / "parcels.geojson")
    print("  copied osm_buildings.geojson, metrics.json, image.png, parcels.geojson")

    layers = {
        "roads": json.loads((PROC_DIR / "roads.geojson").read_text(encoding="utf-8")),
        "railway": json.loads((PROC_DIR / "railway.geojson").read_text(encoding="utf-8")),
        "waterway": json.loads((PROC_DIR / "waterway.geojson").read_text(encoding="utf-8")),
        "government": json.loads((PROC_DIR / "government.geojson").read_text(encoding="utf-8")),
    }
    (OUT_DIR / "layers.json").write_text(json.dumps(layers), encoding="utf-8")
    print("  merged roads/railway/waterway/government -> data/layers.json")

    geo = json.loads((PROC_DIR / "aoi_image_geo.json").read_text(encoding="utf-8"))
    meta = json.loads((PROC_DIR / "meta.json").read_text(encoding="utf-8"))
    (OUT_DIR / "meta.json").write_text(json.dumps({"meta": meta, "image": geo}), encoding="utf-8")
    print("  wrote data/meta.json")

    print("\nStatic bundle ready in frontend/data/. Commit and push frontend/ as-is.")


if __name__ == "__main__":
    main()
